behaviors:
  Defender:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 256
      learning_rate: 0.0003
      learning_rate_schedule: linear
      
      beta: 0.005
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 5
      
    network_settings:
      normalize: false
      hidden_units: 20
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 5000000000
    time_horizon: 32
    summary_freq: 10000
    